
import { 
  Activity,
  BrainCircuit, Shield, Zap, LayoutGrid, Landmark, Key, Coins, 
  Megaphone, Sparkles, ShoppingBag, Bot, Star, MessageSquare, 
  Swords, Cloud, Globe, HardDrive, ShieldCheck, Layers, GitBranch, 
  Terminal, Code, ReceiptText, Gavel, RadioTower, Cpu, Scale, 
  BookOpen, User, Eye, Target, Mic, FlaskConical, Radar, Signal, 
  Crosshair, Scan, MousePointerClick, ClipboardList, Gamepad2, 
  Search, Server, Diamond, Plane, Package, Warehouse, Rocket, 
  Fingerprint, Satellite, Network, Briefcase, Camera, LifeBuoy,
  TrendingUp, AlertTriangle, Atom, Box, Link, Wand2, History, 
  Mail, ListChecks, Swords as WarIcon, MapPin, Map as MapIcon,
  Power, Home, CreditCard, EyeOff, CheckCircle2, Languages,
  Folder, File, Upload, MoreVertical, Download, Trash, Share2,
  Heart, HandMetal, ExternalLink, ShieldAlert,
  FolderArchive, FileCode, CheckCircle2 as CheckCircleIcon,
  Radio, BarChart3, LayoutPanelLeft, ListChecks as ListChecksIcon,
  // FIX: Added missing icon imports
  Settings as SettingsIcon,
  Users, ClipboardList, CreditCard, Building2, Crown, PieChart
} from 'lucide-react';

export const CORE_PERSONAS = [
  { 
    id: 'axiom', 
    name: 'AXIOM_CORE', 
    tier: 'NEXUS', 
    yieldBoost: 0.20, 
    description: 'Neural Convergence Unit. Specialized in high-frequency data sharding and autonomous search grounding.', 
    icon: BrainCircuit, 
    color: 'cyan'
  },
  { 
    id: 'sentinel', 
    name: 'SENTINEL_G', 
    tier: 'NEXUS', 
    yieldBoost: 0.15, 
    description: 'Autonomous Defense Grid. Continuous behavioral ghosting and packet deflection across all nodes.', 
    icon: Shield, 
    color: 'indigo'
  },
  { 
    id: 'wraith', 
    name: 'WRAITH_X', 
    tier: 'NEXUS', 
    yieldBoost: 0.28, 
    description: 'Market Infiltrator. Optimized for unindexed arbitrage vectors and dark-market liquidity extraction.', 
    icon: Zap, 
    color: 'rose'
  }
];

export const MODULES = [
    { id: 'dashboard', label: 'Ecosystem', icon: LayoutGrid, desc: 'Central command for all OS modules.' },
    { id: 'treasury', label: 'Treasury', icon: Landmark, desc: 'Manage Architect licenses & settle capital.' },
    { id: 'key_forge', label: 'Key Forge', icon: Key, desc: 'Manifest Unlimited Access codes for others.', ownerOnly: true },
    { id: 'wealth_matrix', label: 'Wealth Matrix', icon: Coins, desc: 'High-level overview of all income shards.' },
    { id: 'automation_nexus', label: 'Automation', icon: Zap, desc: 'Deploy 30+ real-world income vectors.' },
    { id: 'social_nexus', label: 'Social Nexus', icon: Megaphone, desc: 'Viral infiltration & sentiment sharding.' },
    { id: 'creative_suite', label: 'Creative Suite', icon: Sparkles, desc: 'Access high-fidelity VEO & Image cores.' },
    { id: 'marketplace', label: 'E-Nexus', icon: ShoppingBag, desc: 'Autonomous high-ticket dropshipping.' },
    { id: 'agent', label: 'Swarm Command', icon: Bot, desc: 'Deploy the 250-clone AI workforce.' },
    { id: 'vpersona', label: 'Talent Nexus', icon: Star, desc: 'Manage virtual personas & yield boosts.' },
    { id: 'liaison', label: 'Liaison', icon: MessageSquare, desc: 'Direct neural link to the OS core.' },
    { id: 'warroom', label: 'War Room', icon: WarIcon, desc: 'High-level tactical & defense overview.' },
    { id: 'mainframe', label: 'Mainframe', icon: Cloud, desc: 'State-level sovereign server admin.' },
    { id: 'warden', label: 'Warden', icon: Shield, desc: 'System integrity & threat mitigation.' },
    { id: 'oracle', label: 'Oracle', icon: Globe, desc: 'Ground truth intel from the web.' },
    { id: 'storage', label: 'Quantum Vault', icon: HardDrive, desc: 'Sharded, distributed file storage.' },
    { id: 'security', label: 'Sanctum', icon: ShieldCheck, desc: 'Military-grade security protocols.' },
    { id: 'registry', label: 'Registry', icon: Layers, desc: 'Browse all 144+ system modules.' },
    { id: 'repo_manifest', label: 'Git Shard', icon: GitBranch, desc: 'Access & deploy the OS source code.' },
    { id: 'terminal', label: 'Terminal', icon: Terminal, desc: 'Direct kernel-level command access.' },
    { id: 'ide', label: 'Quantum IDE', icon: Code, desc: 'Architect new system protocols.' },
    { id: 'ledger', label: 'The Ledger', icon: ReceiptText, desc: 'Live market data & economic shards.' },
    { id: 'governance', label: 'Council', icon: Gavel, desc: 'Systemic governance & proposal analysis.' },
    { id: 'thewire', label: 'The Wire', icon: RadioTower, desc: 'Global intelligence briefing stream.' },
    { id: 'compute', label: 'Compute', icon: Cpu, desc: 'Manage tactical cloud server resources.' },
    { id: 'fortress', label: 'Fortress', icon: Swords, desc: 'Defensive protocols & threat intel.' },
    { id: 'equality', label: 'The Equality', icon: Scale, desc: 'Systemic wealth inversion engine.' },
    { id: 'settings', label: 'Settings', icon: SettingsIcon, desc: 'Configure OS & link external shards.' },
    { id: 'help_and_support', label: 'Holo-Deck', icon: BookOpen, desc: 'System intelligence & support.' },
    { id: 'user_profile', label: 'Signature', icon: User, desc: 'Manage your Architect neural identity.' },
    { id: 'sentinel', label: 'Sentinel', icon: Eye, desc: 'Biometric architect monitoring link.' },
    { id: 'mission_manifest', label: 'Mission Hub', icon: Target, desc: 'Targeted high-yield operations.' },
    { id: 'live_neural_link', label: 'The Bridge', icon: Mic, desc: 'Real-time voice link to the OS core.' },
    { id: 'extraction_lab', label: 'The Lab', icon: FlaskConical, desc: 'Generate income blueprints.' },
    { id: 'revenue_radar', label: 'Revenue Radar', icon: Radar, desc: 'Scan for online revenue opportunities.' },
    { id: 'sigint', label: 'SigInt Alpha', icon: Signal, desc: 'Intercept & decrypt commercial signals.' },
    { id: 'strike_command', label: 'Vector Strike', icon: Swords, desc: 'Offensive financial extraction vectors.' },
    { id: 'geospatial', label: 'Local Nexus', icon: MapPin, desc: 'Physical wealth node grounding.' },
    { id: 'infiltrator', label: 'Doc Infiltrator', icon: Scan, desc: 'Analyze documents for intel.' },
    { id: 'impression', label: 'Ad Infiltrator', icon: MousePointerClick, desc: 'Capture yield from ad impressions.' },
    { id: 'sentiment', label: 'Sentiment', icon: ClipboardList, desc: 'Arbitrage market sentiment gaps.' },
    { id: 'yield_arcade', label: 'Arcade', icon: Gamepad2, desc: 'Skill-based yield training.' },
    { id: 'sov_search', label: 'Sovereign Intel', icon: Search, desc: 'Unfiltered, deep-web sourced data.' },
    { id: 'server_admin', label: 'Server Admin', icon: Server, desc: 'Manage military-grade server instances.' },
    { id: 'crypto_hub', label: 'Crypto Hub', icon: Key, desc: 'Quantum-level encryption management.' },
    { id: 'deep_infil', label: 'Deep Infil', icon: Search, desc: 'Unindexed dark-realm sharding.' },
    { id: 'magistrate', label: 'Magistrate', icon: Gavel, desc: 'Governance proposal analysis.' },
    { id: 'decryptor', label: 'Decryptor', icon: Lock, desc: 'Military-grade cipher decomposition.' },
    { id: 'audit_core', label: 'Audit Core', icon: ShieldCheck, desc: 'System integrity and health audits.' },
    { id: 'logistics_nexus', label: 'Drop Shard', icon: Warehouse, desc: 'Logistics & affiliate funnel forge.' },
    { id: 'squad_command', label: 'Squad Hub', icon: Users, desc: 'Multi-node architect collaboration.' },
    { id: 'neural_pulse', label: 'Neural Pulse', icon: BrainCircuit, desc: 'Predict emerging viral trends.' },
    { id: 'travel_nexus', label: 'Terminal', icon: Plane, desc: 'Global travel for foreign market arbitrage.' },
    { id: 'satellite', label: 'Global Ops', icon: Satellite, desc: 'Live coordinate & satellite intel.' },
    { id: 'biosync', label: 'Bio-Sync', icon: Fingerprint, desc: 'Hardware-level biometric sync.' },
    { id: 'mesh', label: 'The Mesh', icon: Network, desc: 'Global persistence network topology.' },
    { id: 'cluster', label: 'Cluster', icon: Layers, desc: 'Orchestrate server cluster resources.' },
    { id: 'holographic_nexus', label: 'Holo World', icon: Diamond, desc: 'Immersive 3D OS environment.' },
  { id: 'platform_treasury', label: 'Platform Treasury', icon: TrendingUp, desc: 'View collected platform fees & revenue.' },
    { id: 'talent_sanctum', label: 'Talent Forge', icon: Star, desc: 'Architect-only 4K virtual model generation.' },
    { id: 'sysdiag', label: 'Diagnostics', icon: Activity, desc: 'Live system kernel diagnostics.' },
    { id: 'campaign_forge', label: 'Growth Hub', icon: Rocket, desc: 'Forge global marketing campaigns.' },
    { id: 'survey_nexus', label: 'High-Ticket Surveys', icon: ClipboardList, desc: 'Complete premium surveys for high yield.' },
    { id: 'payment_portal', label: 'Payment Gateway', icon: CreditCard, desc: 'Secure deposits and upgrades.' },
    { id: 'equity_vault', label: 'Equity Vault', icon: Building2, desc: 'Private equity & asset investment.' },
    { id: 'mastermind_nexus', label: 'Mastermind', icon: Crown, desc: 'Elite networking circles.' },
    { id: 'portfolio', label: 'Portfolio', icon: PieChart, desc: 'Track high-ticket asset performance.' },
];